# This file will contain a script in orde to start up the system (all microservices)
version: "3.7"
services:
  frontend:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
      args:
        - APIURL=http://localhost:8083
    ports:
      - 4200:4200
